apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-zyyg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-zyyg
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-zyyg
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-zyyg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-zyyg
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ntel-tenant/rhtap-demo-app/hacbs-test-project-zyyg@sha256:615a1de19041fde0816d7e560395f40155a36b438b0f8031c1b0ec6822788b62
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
